import os

EMAIL_USER="brygare@gmail.com"
EMAIL_PASS="Ilovebryan$"
AWS_ACCESS_KEY_ID="AKIAQG4433DWZNMZ4REE"
AWS_SECRET_ACCESS_KEY="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"
AWS_STORAGE_BUCKET_NAME="dailybibleverses-files"
SECRET_KEY="5bc585d1297a66e2a029e3de117afc24323515230e6ca707"
DEBUG_VALUE="False"

print(EMAIL_USER)
print(EMAIL_PASS)
print(AWS_ACCESS_KEY_ID)
print(AWS_SECRET_ACCESS_KEY)
print(AWS_STORAGE_BUCKET_NAME)
print(SECRET_KEY)
print(DEBUG_VALUE)
